<?php

    // How long the compiler is allowed to take before it times out (in seconds)
	set_time_limit(120);
	
	// This is the range of switches that Oreo Triggers is allowed to use at a whim. If you don't let it have any then OT is useless, basically.
	switch_range(1, 255);
	
	// Oreo triggers will check for updates each time you compile.
	check_for_updates(true);
	
	
	// Every unit/player combination that is "true" is reserved for Deathcounters. If you set Terran Marine's P8 to "true" that means
	// the system can expect that Player 8 will never suffer any deaths of Terran Marine and the system may potentially designated a
	// Deathcounter with the P8/Marine combination. If you set a player slot to false, then the system will never create a deathcounter
	// with that particular Player/Unit combination.
	// 
	// Units that can potentially die (depending on the map) are commented out. If you need more space allocated for deathcounters, you'll have to 
	// uncomment some of them (thereby adding them to the array).
	$DeathcounterUnits = array(
    'Alan Turret' => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
    'Start Location' => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Goliath Turret' =>  			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Cantina' => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Cave' => 						array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Cave-in' => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Jump Gate' => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Kyadarin Crystal Formation' => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Mining Platform' => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Protoss Unused type 2' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Protoss Unused type 1' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Ruins' => 						array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused Terran Bldg type 2' =>	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused Terran Bldg type 1' =>	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Independent Command Center' => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Independent Starport' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused Zerg Bldg 5' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused Zerg Bldg' => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Protoss Marker' => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Terran Marker' => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Zerg Marker' => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused type 2' => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	'Unused type 1' => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
    'Duke Turret type 2' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
    'Duke Turret type 1' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
    'Tank Turret type 2' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
    'Tank Turret type 1' => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	"Scanner Sweep" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	"Nuclear Missile" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Dark Swarm" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Floor Hatch (UNUSED)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Disruption Field" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Left Pit Door" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Left Upper Level Door" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Map Revealer" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Right Upper Level Door" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Right Pit Door" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Young Chrysalis" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Uraj Crystal" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Psi Emitter" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Data Disc" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Khaydarin Crystal" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Khalis Crystal" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Flag" => 						array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	"Vespene Geyser" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Beacon" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Beacon" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Beacon" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mineral Field (Type 1)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mineral Field (Type 2)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mineral Field (Type 3)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Khaydarin Crystal Formation" =>array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	"Zerg Flag Beacon" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Flag Beacon" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Flag Beacon" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Scarab" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	/**//**/
	"Ion Cannon" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Psi Disrupter" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Alan Schezar (Goliath)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Aldaris (Templar)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Alexei Stukov (Ghost)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Arcturus Mengsk (Battlecruiser)" => array( P1 => true,  P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Artanis (Scout)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Bengalaas (Jungle)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Cocoon" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Danimoth (Arbiter)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Dark Templar (Hero)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Devouring One (Zergling)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Edmund Duke (Siege Mode)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Edmund Duke (Siege Tank)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Fenix (Dragoon)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Fenix (Zealot)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Floor Gun Trap" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Floor Missile Trap" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Gantrithor (Carrier)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Gerard DuGalle (Ghost)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Gui Montag (Firebat)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Hunter Killer (Hydralisk)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Hyperion (Battlecruiser)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Infested Command Center" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Infested Duran" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Infested Kerrigan (Infested Terran)" => array( P1 => true,  P2 => true, P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Infested Terran" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Jim Raynor (Marine)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Jim Raynor (Vulture)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Kakaru (Twilight)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Kukulza (Guardian)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Kukulza (Mutalisk)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Left Wall Flame Trap" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Left Wall Missile Trap" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Magellan (Science Vessel)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Matriarch (Queen)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mature Crysalis" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mineral Chunk (Type 1)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mineral Chunk (Type 2)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Mojo (Scout)" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Norad II (Battlecruiser)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Norad II (Crashed Battlecruiser)" => array( P1 => true, P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Overmind Cocoon" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Power Generator" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Arbiter" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Arbiter Tribunal" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Archon" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Assimilator" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Carrier" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Citadel of Adun" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Corsair" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Cybernetics Core" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Dark Archon" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Dark Templar" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Dragoon" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Fleet Beacon" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Forge" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Gateway" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss High Templar" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Interceptor" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Nexus" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Observatory" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Observer" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Photon Cannon" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Probe" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Pylon" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Reaver" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Robotics Facility" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Robotics Support Bay" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Scout" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Shield Battery" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Shuttle" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Stargate" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Templar Archives" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Temple" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Protoss Zealot" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Ragnasaur (Ash World)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Raszagal (Dark Templar)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Rhynadon (Badlands)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Right Wall Flame Trap" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Right Wall Missile Trap" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Samir Duran (Ghost)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Sarah Kerrigan (Ghost)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Scantid (Desert)" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Stasis Cell/Prison" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Tassadar (Templar)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Tassadar/Zeratul (Archon)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Academy" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Armory" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Barracks" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Battlecruiser" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Bunker" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Civilian" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Command Center" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Comsat Station" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Control Tower" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Covert Ops" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Dropship" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Engineering Bay" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Factory" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Firebat" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Ghost" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Goliath" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Machine Shop" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ),
	/**//**
	"Terran Marine" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Medic" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Missile Turret" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Nuclear Silo" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Physics Lab" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Refinery" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Science Facility" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Science Vessel" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran SCV" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Siege Tank (Siege Mode)" => array( P1 => true,  P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Siege Tank (Tank Mode)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Starport" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Supply Depot" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Valkyrie" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Vulture" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Terran Wraith" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Tom Kazansky (Wraith)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Torrasque (Ultralisk)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Unclean One (Defiler)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Ursadon (Ice World)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Orb (Protoss Type 1)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Orb (Protoss Type 2)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Sac (Zerg Type 1)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Sac (Zerg Type 2)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Tank (Terran Type 1)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vespene Tank (Terran Type 2)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Vulture Spider Mine" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Warbringer (Reaver)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Warp Gate" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Xel'Naga Temple" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Yggdrasill (Overlord)" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zeratul (Dark Templar)" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Broodling" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Cerebrate" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Cerebrate Daggoth" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Creep Colony" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Defiler" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Defiler Mound" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Devourer" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Drone" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Egg" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Evolution Chamber" => 	array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Extractor" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Greater Spire" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Guardian" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Hatchery" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Hive" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Hydralisk" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Hydralisk Den" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Lair" => 					array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Larva" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Lurker" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Lurker Egg" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Mutalisk" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Nydus Canal" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Overlord" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Overmind" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Overmind (With Shell)" => array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Queen" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Queen's Nest" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Scourge" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Spawning Pool" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Spire" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Spore Colony" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Sunken Colony" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Ultralisk" => 			array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Ultralisk Cavern" => 		array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	"Zerg Zergling" => 				array( P1 => true,  	P2 => true,  	P3 => true, 	P4 => true, 	P5 => true, 	P6 => true, 	P7 => true, 	P8 => true ), 
	/**/
	);
	
	
?>